site_name: LeetCode
site_author: Abdulaminkhon Khaydarov
site_description: LeetCode Masalalar Javoblari
site_url: https://leetcode.webdastur.uz

theme:
  name: material
  palette: 
    scheme: slate
    primary: teal
    accent: orange
  font:
    text: Inter
    code: JetBrains Mono
  language: uz
  icon:
    repo: fontawesome/brands/github
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - content.code.annotate
    - navigation.instant
    - navigation.top

plugins:
  - search
  - git-revision-date-localized:
      type: datetime
      fallback_to_build_date: true
      enable_creation_date: false
      enabled: true


extra:
  generator: true
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/webdastur
      name: webdastur
    - icon: fontawesome/brands/youtube
      link: https://bit.ly/AlexTechUz
      name: AlexTechUz


copyright: Copyright &copy; 2016 - 2022 Abdulaminkhon Khaydarov
repo_url: https://github.com/webdastur/leetcode
repo_name: webdastur/leetcode
edit_uri: ""

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.magiclink
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_css:
  - stylesheets/extra.css

nav:
  - Kirish: index.md
  - Array:
    - 🟢 Easy:
        - 1920 - Build Array from Permutation: array/easy/1920-build-array-from-permutation.md
    - 🟠 Medium: ..
    - 🔴 Hard: ..